app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', 'GalleryController@showAlbums');
Route::get('all', 'GalleryController@showAllImages');
Route::get('import', 'GalleryController@import');

Route::get('{album_folder}', 'GalleryController@showAlbum');
Route::get('{album_folder}/{image_file}', 'GalleryController@showImage');

app/models/Album.php
<?php

class Album extends Eloquent {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'albums';

	protected $guarded = array();

	public static $rules = array(
		// 'name'          => 'required',
		// 'logo_url'      => 'required',
		// 'description'   => 'required',
		// 'game_start'    => 'required|date',
		// 'contact_email' => 'email',
	);

	public function images()
	{
		return $this->hasMany('Image');
	}

	public function getImageIdAttribute($value)
	{
		if ($value)
		{
			$image = Image::find($value);
		}
		else
		{
			$image = Image::where('album_id', $this->id)->first();
		}

		return ($image) ? $image->thumburl : '';
	}

}

app/models/Image.php
<?php

class Image extends Eloquent {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'images';

	protected $guarded = array();

	public static $rules = array(
		// 'name'          => 'required',
		// 'logo_url'      => 'required',
		// 'description'   => 'required',
		// 'game_start'    => 'required|date',
		// 'contact_email' => 'email',
	);

	public function album()
	{
		return $this->belongsTo('Album');
	}

	public function getImageurlAttribute($value)
	{
		$album = Album::find($this->album_id);
		return Config::get('filegallery.imagesfolder').'/'.$album->folder.'/'.$this->image;
	}

	public function getThumburlAttribute()
	{
		$album = Album::find($this->album_id);
		return Config::get('filegallery.imagesfolder').'/'.$album->folder.'/thumbs/'.$this->image;
	}

}

app/views/album.blade.php
@extends('layouts.scaffold')

@section('meta')
	<meta property="og:type"            content="article" />
	<meta property="og:site_name"       content="{{ Config::get('filegallery.page.title') }}"/>
	<meta property="og:url"             content="{{ url($album->folder) }}" />
	<meta property="og:title"           content="{{ $album->title }}" />
	<meta name="description"            content="An album from the site: {{ Config::get('filegallery.page.title') }}">
	<meta property="og:description"     content="An album from the site: {{ Config::get('filegallery.page.title') }}">

	<meta name="twitter:card"           content="gallery">
	<meta name="twitter:url"            content="{{ url($album->folder) }}">
	<meta name="twitter:title"          content="{{ $album->title }}">
	<meta name="twitter:description"    content="An album from the site: {{ Config::get('filegallery.pagetitle') }}">
@if ($album->images->count() > 4)
@for ($i=0; $i < 4; $i++)
	<meta name="twitter:image{{ $i }}"         content="{{ url($album->folder.'/'.$album->images[$i]->image) }}">
@endfor
@endif

@stop


@section('main')

<ol class="breadcrumb">
	<li><a href="{{ url('/') }}">Albums</a></li>
	<li class="active">{{ $album->title }}</li>
</ol>

@if ($album->images->count())
	<div class="page-header">
		<h1 class="text-center">{{ $album->title }}</h1>
	</div>
	<div class="row">
	<?php $counter = 1 ?>
	@foreach ($album->images as $image)
		<div class="grid image col-xs-4 col-sm-3 col-md-2 col-lg-2">
			<a href="{{ url($image->album->folder.'/'.$image->image) }}" caption=" {{ $image->text }}" imgpage="{{ url($image->album->folder.'/'.$image->image) }}">
				<span class="dim"></span>
				<img src="{{ asset($image->thumburl) }}" class="img-responsive" alt="{{ $image->title }}">
			</a>
		</div>
		<?php
			$clearfixes = '';
			if ($counter % 3 == 0) { $clearfixes .= ' visible-xs'; }
			if ($counter % 4 == 0) { $clearfixes .= ' visible-sm'; }
			if ($counter % 6 == 0) { $clearfixes .= ' visible-md visible-lg'; }

			$counter++;
		?>
		@if ( $clearfixes != '' )
			<div class="clearfix {{ $clearfixes }}"></div>
		@endif
	@endforeach
	</div>
@else
	There are no images in this album
@endif

@stop

app/views/albums.blade.php
@extends('layouts.scaffold')

@section('meta')
	<meta property="og:type"            content="article" />
	<meta property="og:site_name"       content="{{ Config::get('filegallery.page.title') }}"/>
	<meta property="og:url"             content="{{ url('/') }}" />
	<meta property="og:title"           content="{{ Config::get('filegallery.page.title') }}" />
	<meta name="description"            content="Welcome to the online gallery {{ Config::get('filegallery.pagetitle') }}">
	<meta property="og:description"     content="Welcome to the online gallery {{ Config::get('filegallery.pagetitle') }}">

	<meta name="twitter:card"           content="summary">
	<meta name="twitter:url"            content="{{ url('/') }}">
	<meta name="twitter:title"          content="{{ Config::get('filegallery.page.title') }}">
	<meta name="twitter:description"    content="Welcome to the online gallery {{ Config::get('filegallery.pagetitle') }}">
@stop


@section('main')

<ol class="breadcrumb">
	<li class="active">Albums</li>
</ol>

<div class="page-header">
	<h1 class="text-center">Albums</h1>
</div>
@if ($albums->count())
	<div class="row">
		<?php $counter = 1 ?>
		@foreach ($albums as $album)
			<div class="grid album col-xs-4 col-sm-3 col-md-2 col-lg-2">
				<a href="{{ url($album->folder) }}">
					<span class="dim"></span>
					<img src="{{ asset($album->image_id) }}" class="img-responsive" alt="{{ $album->title }}">
					<span class="title label label-default">{{ $album->title }}</span>
				</a>
			</div>
			<?php
				$clearfixes = '';
				if ($counter % 3 == 0) { $clearfixes .= ' visible-xs'; }
				if ($counter % 4 == 0) { $clearfixes .= ' visible-sm'; }
				if ($counter % 6 == 0) { $clearfixes .= ' visible-md visible-lg'; }

				$counter++;
			?>
			@if ( $clearfixes != '' )
				<div class="clearfix {{ $clearfixes }}"></div>
			@endif
		@endforeach
	</div>
@else
	There are no albums
@endif

@stop

app/views/all.blade.php
@extends('layouts.scaffold')

@section('main')

@if ($albums->count())
	@foreach ($albums as $album)
		<div class="row">

		@if ($album->images->count())
			<div class="page-header">
				<h1 class="text-center">{{ $album->title }}</h1>
			</div>
			<div class="row">
			<?php $counter = 1 ?>
			@foreach ($album->images as $image)
				<div class="grid image col-xs-4 col-sm-3 col-md-2 col-lg-2">
					<a href="{{ url($image->album->folder.'/'.$image->image) }}" caption=" {{ $image->text }}" imgpage="{{ url($image->album->folder.'/'.$image->image) }}">
						<span class="dim"></span>
						<img src="{{ asset($image->thumburl) }}" class="img-responsive" alt="{{ $image->title }}">
					</a>
				</div>
				<?php
					$clearfixes = '';
					if ($counter % 3 == 0) { $clearfixes .= ' visible-xs'; }
					if ($counter % 4 == 0) { $clearfixes .= ' visible-sm'; }
					if ($counter % 6 == 0) { $clearfixes .= ' visible-md visible-lg'; }

					$counter++;
				?>
				@if ( $clearfixes != '' )
					<div class="clearfix {{ $clearfixes }}"></div>
				@endif
			@endforeach
			</div>
		@else
			There are no images in this album
		@endif
		</div>
	@endforeach
@else
	There are no albums
@endif

@stop

app/views/image.blade.php
@extends('layouts.scaffold')

@section('meta')
	<meta property="og:type"            content="article" />
	<meta property="og:site_name"       content="{{ Config::get('filegallery.page.title') }}"/>
	<meta property="og:url"             content="{{ url($image->album->folder.'/'.$image->image) }}" />
	<meta property="og:title"           content="{{ $image->title }}" />
	<meta name="description"            content="{{ ($image->text) ? html_entity_decode(strip_tags($image->text),ENT_QUOTES,'UTF-8') : 'Image from the album '.$image->album->title }}">
	<meta property="og:description"     content="{{ ($image->text) ? html_entity_decode(strip_tags($image->text),ENT_QUOTES,'UTF-8') : 'Image from the album '.$image->album->title }}">
	<meta property="og:image"           content="{{ asset($image->imageurl) }}" />

	<meta name="twitter:card"           content="photo">
	<meta name="twitter:url"            content="{{ url($image->album->folder.'/'.$image->image) }}">
	<meta name="twitter:title"          content="{{ $image->title }}">
	<meta name="twitter:description"    content="{{ ($image->text) ? html_entity_decode(strip_tags($image->text),ENT_QUOTES,'UTF-8') : 'Image from the album '.$image->album->title }}">
	<meta name="twitter:image"          content="{{ asset($image->imageurl) }}">
@stop


@section('main')

		<ol class="breadcrumb">
			<li><a href="{{ url('/') }}">Albums</a></li>
			<li><a href="{{ url($image->album->folder) }}">{{ $image->album->title }}</a></li>
			<li class="active">{{ $image->title }}</li>
		</ol>

@if ($image)
	<div class="row">
		<div id="imagenav" class="navigation text-center col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<a id="prev-img" href="{{ url($image->album->folder.'/'.$image->prev->image) }}" class="btn">
				<span class="glyphicon glyphicon-chevron-left"></span>
			</a>
			<a id="next-img" href="{{ url($image->album->folder.'/'.$image->next->image) }}" class="btn">
				<span class="glyphicon glyphicon-chevron-right"></span>
			</a>
		</div>
	</div>

	<div class="row">
		<div class="fullimagecontainer col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div id="loader" class="loading fullimage" rel="fitimage" imgfile="{{ asset($image->imageurl) }}">
				{{-- Here the image will be loaded --}}
			</div>
		</div>
	</div>

	@if ($image->text)
	<div class="row">
		<div class="text-center col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="img-description">{{ $image->text }}</div>
		</div>
	</div>
	@endif

	<div class="social">
		<?php
			$share = array(
				'url'   => url($image->album->folder.'/'.$image->image),
				'image' => asset($image->imageurl),
				'text'  => $image->text,
			);

			$facebook_like =
				'http://www.facebook.com/plugins/like.php' .
				'?href=' . $share['url'] .
				'&width=450&height=21&colorscheme=light&layout=button_count' .
				'&action=like&show_faces=false&send=false' .
				'&appId=' . Config::get('filegallery.fb_app_id');

			$pinterest =
				'http://pinterest.com/pin/create/button/' .
				'?url=' . $share['url'] .
				'&media=' . $share['image'];

			if ($share['text']) {
				$pinterest .= '&description=' . $share['text'];
			}

			$twitter = array(
				'url'     => url($image->album->folder.'/'.$image->image),
				'text'    => $image->text,
				'via'     => null,
				'hashtag' => null,
			);

		?>

		<div class="social_links fb_likes">
			<fb:like href="{{ $share['url'] }}" width="140" layout="button_count" show_faces="false" send="true"></fb:like>
		</div>
		<div class="social_links twitter">
			<a href="https://twitter.com/share" class="twitter-share-button" data-url="{{ $twitter['url'] }}" {{ ($twitter['text']) ? 'data-text="'.$twitter['text'].'"' : '' }} {{ ($twitter['via']) ? 'data-via="'.$twitter['via'].'"' : '' }} {{ ($twitter['hashtag']) ? 'data-hashtags="'.$twitter['hashtag'].'"' : '' }}>Tweet</a>
			<script>
				!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
			</script>
		</div>
		<div class="social_links pinterest">
			<a href="{{ $pinterest }}" data-pin-do="buttonPin" data-pin-config="beside" target="_blank"><img src="//assets.pinterest.com/images/pidgets/pin_it_button.png" /></a>
		</div>
	</div>
	<div class="comments">
		<fb:comments href="{{ url($image->album->folder.'/'.$image->image) }}"></fb:comments>
	</div>
@else
	No image
@endif

@stop